version: '3'
services:
  auth_node:
    container_name: auth_node
    restart: always
    build: auth/
    ports:
      - '3000:3000'
    links:
      - auth_mongo
  auth_mongo:
    container_name: auth_mongo
    image: mongo
    restart: always 
    volumes: 
      - ./data:/data/db
