version: '3'
services:
  server:
    container_name: node
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    volumes: 
      - ./data:/data/db
